import styles from '@/styles/globals.css'

export const metadata = {
  title: 'Kare Matters, LLC | Designing Beautiful Futures | Plano, TX',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        {/* Navbar socket */}
        {/* Navbar */}
        {children}
        {/* Testimonials */}
        {/* Footer */}
        {/* Footer socket */}
      </body>
    </html>
  )
}
