import Footer from '@/components/footer/Footer'
import FooterSocket from '@/components/footer/FooterSocket'
import Navbar from '@/components/navbar/Navbar'
import NavbarSocket from '@/components/navbar/NavbarSocket'
import TestimonialsContainer from '@/components/testimonials/TestimonialsContainer'
import { Poppins } from 'next/font/google'
import '@/styles/globals.css'

export const metadata = {
  title: 'Kare Matters, LLC | Designing Beautiful Futures | Plano, TX',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <NavbarSocket />
        <Navbar />
        {children}
        <TestimonialsContainer />
        <Footer />
        <FooterSocket />
      </body>
    </html>
  )
}
