import Navbar from '@/components/navbar/Navbar'
import NavbarSocket from '@/components/navbar/NavbarSocket'
import styles from '@/styles/globals.css'

export const metadata = {
  title: 'Kare Matters, LLC | Designing Beautiful Futures | Plano, TX',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <NavbarSocket />
        <Navbar />
        {children}
        {/* Testimonials */}
        {/* Footer */}
        {/* Footer socket */}
      </body>
    </html>
  )
}
